name: Combined CI Workflow

on:
  create:
    tags: 
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  DEVELOPER: 1

concurrency:
  group: ${{ github.sha }}

jobs:

  npm-install:
    name: Install npm and Node.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/checkout@v4
      - name: Install Nvm
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash

      - name: download and install Node.js (you may need to restart the terminal)
        run: nvm install 22

      - name: verifies the right Node.js version is in the environment
        run: node -v # should print `v22.11.0`

      - name: verifies the right npm version is in the environment
        run: npm -v # should print `10.9.0`
