name: ci

on:
- pull_request
- push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
        - Node.js 0.8
        - Node.js 0.10
        - Node.js 0.12
        - io.js 1.x
        - io.js 2.x
        - io.js 3.x
        - Node.js 4.x
        - Node.js 5.x
        - Node.js 6.x
        - Node.js 7.x
        - Node.js 8.x
        - Node.js 9.x
        - Node.js 10.x
        - Node.js 11.x
        - Node.js 12.x
        - Node.js 13.x
        - Node.js 14.x
        - Node.js 15.x

        include:
        - name: Node.js 0.8
          node-version: "0.8"
          npm-i: mocha@2.5.3
          npm-rm: nyc

        - name: Node.js 0.10
          node-version: "0.10"
          npm-i: browserify@15 mocha@3.5.3 nyc@10.3.2

        - name: Node.js 0.12
          node-version: "0.12"
          npm-i: browserify@15 mocha@3.5.3 nyc@10.3.2

        - name: io.js 1.x
          node-version: "1.8"
          npm-i: browserify@15 mocha@3.5.3 nyc@10.3.2

        - name: io.js 2.x
          node-version: "2.5"
          npm-i: browserify@15 mocha@3.5.3 nyc@10.3.2

        - name: io.js 3.x
          node-version: "3.3"
          npm-i: browserify@15 mocha@3.5.3 nyc@10.3.2

        - name: Node.js 4.x
          node-version: "4.9"
          npm-i: browserify@15 mocha@5.2.0 nyc@11.9.0

        - name: Node.js 5.x
          node-version: "5.12"
          npm-i: browserify@15 mocha@5.2.0 nyc@11.9.0

        - name: Node.js 6.x
          node-version: "6.17"
          npm-i: browserify@15 mocha@6.2.2 nyc@14.1.1

        - name: Node.js 7.x
          node-version: "7.10"
          npm-i: browserify@15 mocha@6.2.2 nyc@14.1.1

        - name: Node.js 8.x
          node-version: "8.17"
          npm-i: browserify@15 mocha@7.2.0

        - name: Node.js 9.x
          node-version: "9.11"
          npm-i: browserify@15 mocha@7.2.0

        - name: Node.js 10.x
          node-version: "10.23"
          npm-i: browserify@15

        - name: Node.js 11.x
          node-version: "11.15"
          npm-i: browserify@15

        - name: Node.js 12.x
          node-version: "12.20"
          npm-i: browserify@15

        - name: Node.js 13.x
          node-version: "13.14"
          npm-i: browserify@15

        - name: Node.js 14.x
          node-version: "14.15"
          npm-i: browserify@15

        - name: Node.js 15.x
          node-version: "15.8"
          npm-i: browserify@15

    steps:
    - uses: actions/checkout@v2

    - name: Remove non-test npm modules
      run: npm rm --silent --save-dev benchmark beautify-benchmark

    - name: Remove npm module(s) ${{ matrix.npm-rm }}
      run: npm rm --silent --save-dev ${{ matrix.npm-rm }}
      if: matrix.npm-rm != ''

    - name: Install npm module(s) ${{ matrix.npm-i }}
      run: npm install --save-dev ${{ matrix.npm-i }} 
      if: matrix.npm-i != ''

    - name: Fix with Audit - npm
      run: npm audit fix --force

    - name: Fix audit (2)
      run: npm audit fix --force
  
    - name: Lint code
      if: steps.list_env.outputs.eslint != ''
      run: npm run lint

    - name: Collect code coverage
      if: steps.list_env.outputs.nyc != ''
      run: |
        if [[ -d ./coverage ]]; then
          mv ./coverage "./${{ matrix.name }}"
          mkdir ./coverage
          mv "./${{ matrix.name }}" "./coverage/${{ matrix.name }}"
        fi

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install lcov
      shell: bash
      run: sudo apt-get -y install lcov

    - name: Collect coverage reports
      uses: actions/download-artifact@v4.1.7
      with:
        name: coverage
        path: ./coverage

    - name: Merge coverage reports
      shell: bash
      run: find ./coverage -name lcov.info -exec printf '-a %q\n' {} \; | xargs lcov -o ./coverage/lcov.info

    - name: Upload coverage report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
