name: Example Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo a bold message
        run: |
          echo "::group::My Bold Message"
          echo "**This is a bold message**"
          echo "::endgroup::"
